version: '3'
services:
  phpfpm:
    environment:
        DB_NAME: bitnami_wordpress
        DB_USER: bn_wordpress
        DB_PASSWORD: 9494647662
        DB_HOST: mbird-mag.cluster-chc5sxkp1qgh.us-east-1.rds.amazonaws.com
        DB_TABLE_PREFIX: mag_
    volumes:
      - "./wordpress-mag:/var/www/html"
  nginx:
    volumes:
      - "./wordpress-mag:/var/www/html"
    environment:
              VIRTUAL_HOST: mag.docker
